
project_id = "bnulocsnxiffavvabfdj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions]
verify_jwt = false

[functions.get-bunny-video-details]
verify_jwt = false

[functions.login-cartorio]
verify_jwt = false

[functions.upload-video-bunny]
verify_jwt = false

[functions.get-video-url]
verify_jwt = true

[functions.chat-ai]
verify_jwt = false

[functions.bunny-webhook]
verify_jwt = false

[functions.get-cartorio-id]
verify_jwt = false

[functions.get-sistemas-cartorio]
verify_jwt = false

[functions.get-sistemas-cartorio-with-permissions]
verify_jwt = false


[functions.update-cartorio-permissions]
verify_jwt = true

[functions.admin-auth]
verify_jwt = false

[functions.get-cartorios-admin]
verify_jwt = false

[functions.get-admin-stats]
verify_jwt = false

[functions.get-cartorio-permissions]
verify_jwt = false

[functions.delete-cartorio]
verify_jwt = false

[functions.update-bunny-video-ids]
verify_jwt = true

[functions.verify-token]
verify_jwt = false

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
