
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnulocsnxiffavvabfdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJudWxvY3NueGlmZmF2dmFiZmRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzM1NTMsImV4cCI6MjA2NjQ0OTU1M30.3QeKQtbvTN4KQboUKhqOov16HZvz-xVLxmhl70S2IAE";

// Singleton pattern: Uma única instância do cliente Supabase para toda a aplicação
let supabaseInstance: ReturnType<typeof createClient<Database>> | null = null;

// Função para obter a instância única do cliente Supabase
const getSupabaseInstance = () => {
  if (!supabaseInstance) {
    console.log('🔧 [Supabase] Creating single client instance');
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        persistSession: true, // Mantém a sessão persistente para admins
        autoRefreshToken: true, // Auto-refresh de tokens
        detectSessionInUrl: true,
      },
      global: {
        headers: {},
      },
    });
  }
  return supabaseInstance;
};

// Export da instância única
export const supabase = getSupabaseInstance();

// Sistema de gerenciamento de contexto de autenticação para cartórios
class AuthContextManager {
  private currentToken: string | null = null;
  private currentHeaders: Record<string, string> = {};

  setCartorioContext(token: string) {
    console.log('🔐 [AuthContext] Setting cartorio context with token type:', token.startsWith('CART-') ? 'CART token' : 'Other token');
    
    this.currentToken = token;
    this.currentHeaders = {};
    
    // Para tokens de cartório, configurar headers customizados
    if (token.startsWith('CART-')) {
      this.currentHeaders = {
        'Authorization': `Bearer ${token}`,
        'X-Custom-Auth': token,
      };
    } else {
      this.currentHeaders = {
        'Authorization': `Bearer ${token}`,
      };
    }
  }

  clearContext() {
    console.log('🔐 [AuthContext] Clearing cartorio context');
    this.currentToken = null;
    this.currentHeaders = {};
  }

  getHeaders(): Record<string, string> {
    return { ...this.currentHeaders };
  }

  hasContext(): boolean {
    return this.currentToken !== null;
  }

  getCurrentToken(): string | null {
    return this.currentToken;
  }
}

// Instância única do gerenciador de contexto
const authContextManager = new AuthContextManager();

// Função para configurar o contexto de autenticação de cartório
export const setCartorioAuthContext = (token: string) => {
  authContextManager.setCartorioContext(token);
};

// Função para limpar o contexto de autenticação de cartório
export const clearCartorioAuthContext = () => {
  authContextManager.clearContext();
};

// Função para obter cliente com contexto de autenticação apropriado
export const getAuthenticatedClient = () => {
  const client = getSupabaseInstance();
  
  // Se há contexto de cartório, aplicar headers
  if (authContextManager.hasContext()) {
    const headers = authContextManager.getHeaders();
    console.log('🔐 [AuthContext] Applying cartorio headers to request');
    
    // Retorna uma versão do cliente com headers customizados
    return {
      ...client,
      from: (table: string) => {
        return client.from(table).select('*', { 
          head: false,
          headers 
        });
      },
      rpc: (fn: string, args?: any) => {
        return client.rpc(fn, args, { headers });
      }
    };
  }
  
  // Para casos padrão (admin), retorna o cliente normal
  return client;
};

// Helper function compatível com o código existente
export const createAuthenticatedClient = (token: string) => {
  console.log('🔐 [createAuthenticatedClient] Setting up context for token type:', token.startsWith('CART-') ? 'CART token' : 'Other token');
  
  // Em vez de criar nova instância, configuramos o contexto
  setCartorioAuthContext(token);
  
  // Retorna a instância única configurada
  return getAuthenticatedClient();
};

// Funções de compatibilidade (mantidas para não quebrar código existente)
export const setCustomAuthToken = (token: string) => {
  console.log('Setting custom auth token via compatibility function:', token);
  setCartorioAuthContext(token);
};

export const clearCustomAuthToken = () => {
  console.log('Clearing custom auth token via compatibility function');
  clearCartorioAuthContext();
};
